server:
  port: 8080
spring:
  application:
    name: testingDemo
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootTestingDemoDatabase
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
